/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main.java.View;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;

import main.java.Controller.ClienteController;
import main.java.Controller.ReservaController;
import main.java.model.Cliente;
import main.java.model.Reserva;
import main.java.resources.conversor.Conversor;

/**
 *
 * @author HP - 4300
 */
public class MinhasReserv extends javax.swing.JFrame {

	private static Cliente cliente = new Cliente();
	private final Reserva r;
	private final ClienteController controller;
	private final ReservaController reservaController;
	private static List<Reserva> listaReserva = new ArrayList<>();

	/**
	 * Creates new form MinhasReserv
	 */
	public MinhasReserv() {
		initComponents();
		this.setDefaultCloseOperation(0);
		r = new Reserva();
		reservaController = new ReservaController();
		controller = new ClienteController();
		preecherTabela();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		txtChegada = new javax.swing.JFormattedTextField();
		txtHora = new javax.swing.JFormattedTextField();
		txtSaida = new javax.swing.JFormattedTextField();
		btnEditar = new javax.swing.JButton();
		btnCancelar = new javax.swing.JButton();
		btnVoltar = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		tabelaReserva = new javax.swing.JTable();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Minhas Reservas");
		setResizable(false);

		jLabel1.setText("Chegada:");

		jLabel2.setText("Saída:");

		jLabel3.setText("Hora:");

		try {
			txtChegada.setFormatterFactory(
					new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
		} catch (java.text.ParseException ex) {
			ex.printStackTrace();
		}
		txtChegada.setHorizontalAlignment(SwingConstants.CENTER);

		try {
			txtHora.setFormatterFactory(
					new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
		} catch (java.text.ParseException ex) {
			ex.printStackTrace();
		}
		txtHora.setHorizontalAlignment(SwingConstants.CENTER);

		try {
			txtSaida.setFormatterFactory(
					new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
		} catch (java.text.ParseException ex) {
			ex.printStackTrace();
		}
		txtSaida.setHorizontalAlignment(SwingConstants.CENTER);

		btnEditar.setBackground(new java.awt.Color(255, 153, 0));
		btnEditar.setForeground(new java.awt.Color(255, 255, 255));
		btnEditar.setText("Editar");
		btnEditar.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnEditarActionPerformed(evt);
			}
		});

		btnCancelar.setBackground(new java.awt.Color(204, 0, 0));
		btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
		btnCancelar.setText("Cancelar");
		btnCancelar.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnCancelarActionPerformed(evt);
			}
		});

		btnVoltar.setBackground(new java.awt.Color(51, 51, 51));
		btnVoltar.setForeground(new java.awt.Color(255, 255, 255));
		btnVoltar.setText("Voltar");
		btnVoltar.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnVoltarActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(86, 86, 86)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addGroup(jPanel1Layout.createSequentialGroup().addComponent(jLabel3)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 108,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(jPanel1Layout.createSequentialGroup().addComponent(jLabel2)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(txtSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 108,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(jPanel1Layout.createSequentialGroup().addComponent(jLabel1)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(txtChegada, javax.swing.GroupLayout.PREFERRED_SIZE, 108,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addGap(29, 29, 29)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(btnVoltar, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(11, 11, 11)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel1)
								.addComponent(txtChegada, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btnEditar))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel3)
								.addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btnCancelar))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel2)
								.addComponent(txtSaida, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btnVoltar))
						.addContainerGap(14, Short.MAX_VALUE)));

		tabelaReserva.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {

		}, new String[] { "Id", "Entrada", "Saida", "Hora", "Quarto", "Status", "Valor" }) {
			boolean[] canEdit = new boolean[] { false, false, false, false, false, false, true };

			@Override
			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
		tabelaReserva.addMouseListener(new java.awt.event.MouseAdapter() {
			@Override
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				tabelaReservaMouseClicked(evt);
			}
		});
		jScrollPane1.setViewportView(tabelaReserva);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)));

		pack();
		setLocationRelativeTo(null);
	}// </editor-fold>//GEN-END:initComponents

	private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnEditarActionPerformed
		if (tabelaReserva.getSelectedRowCount() == 1) {
			int indice = tabelaReserva.getSelectedRow();
			Reserva reserva = listaReserva.get(indice);
			if (("cancelada").equals(reserva.getStatus()) || ("recusada").equals(reserva.getStatus()) || ("aprovada").equals(reserva.getStatus())) {
				
				JOptionPane.showMessageDialog(this, "Opção inválida!", "Erro!", JOptionPane.ERROR_MESSAGE);
				
			} else {
				boolean dataMaiorOuIgualAtual = false;
				boolean dataInicialMaiorOuigualFinal = false;
				boolean dataInicialMenorQueAtual = false;
				LocalDate inicial = Conversor.ConversorData(txtChegada.getText());
				LocalDate fim = Conversor.ConversorData(txtSaida.getText());
				if (Conversor.DataInicioMaiorQueAtual(inicial) || Conversor.DataInicioIgualAtual(inicial)) {
					dataMaiorOuIgualAtual = true;
				}
				if (Conversor.DataInicMenorQueFinal(inicial, fim) || Conversor.DataInicioIgualFinal(inicial, fim)) {
					dataInicialMaiorOuigualFinal = true;
				}
				if (Conversor.DataInicioMenorQueAtual(inicial)) {
					dataInicialMenorQueAtual = true;
				}
				if (dataInicialMaiorOuigualFinal && dataMaiorOuIgualAtual && !dataInicialMenorQueAtual) {
					reserva.setDataInicial(inicial);
					reserva.setDataFinal(fim);
					reserva.setHoraEntrada(Conversor.ConversorHora(txtHora.getText()));
					reserva.setCpf_cliente(cliente.getCpf());
					reservaController.AtualizarReserva(reserva);
					preecherTabela();
				} else {
					JOptionPane.showMessageDialog(this, "Opção inválida!", "Erro!", JOptionPane.ERROR_MESSAGE);
				}
			}
		}
	}// GEN-LAST:event_btnEditarActionPerformed

	private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCancelarActionPerformed
		if (JOptionPane.showConfirmDialog(this, "Deseja realmente cancelar?", "Confirmação", JOptionPane.YES_NO_OPTION,
				JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {
			if (tabelaReserva.getSelectedRowCount() == 1) {
				int indice = tabelaReserva.getSelectedRow();
				Reserva reserva = listaReserva.get(indice);
				if (("cancelada").equals(reserva.getStatus()) || ("recusada").equals(reserva.getStatus()) || ("aprovada").equals(reserva.getStatus())) {
					
					JOptionPane.showMessageDialog(this, "Opção inválida!", "Erro!", JOptionPane.ERROR_MESSAGE);
					
				} else {
					reserva.setStatus("cancelada");
					reserva.setCpf_cliente(cliente.getCpf());
					reservaController.AtualizarReserva(reserva);
					preecherTabela();
				}
			}
		}
	}// GEN-LAST:event_btnCancelarActionPerformed

	private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnVoltarActionPerformed
		this.dispose();
	}// GEN-LAST:event_btnVoltarActionPerformed

	private void tabelaReservaMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_tabelaReservaMouseClicked
		txtChegada.setText(tabelaReserva.getValueAt(tabelaReserva.getSelectedRow(), 1).toString());
		txtHora.setText(tabelaReserva.getValueAt(tabelaReserva.getSelectedRow(), 3).toString());
		txtSaida.setText(tabelaReserva.getValueAt(tabelaReserva.getSelectedRow(), 2).toString());
	}// GEN-LAST:event_tabelaReservaMouseClicked

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MinhasReserv.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MinhasReserv.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MinhasReserv.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MinhasReserv.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			@Override
			public void run() {
				new MinhasReserv().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnCancelar;
	private javax.swing.JButton btnEditar;
	private javax.swing.JButton btnVoltar;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable tabelaReserva;
	private javax.swing.JFormattedTextField txtChegada;
	private javax.swing.JFormattedTextField txtHora;
	private javax.swing.JFormattedTextField txtSaida;
	// End of variables declaration//GEN-END:variables

	public void preecherTabela() {
		listaReserva = reservaController.listAll(cliente.getCpf());
		DefaultTableModel model = (DefaultTableModel) tabelaReserva.getModel();
		model.setRowCount(0);
		for (Reserva reserva : listaReserva) {
			model.addRow(new Object[] { reserva.getId(), Conversor.conversorData(reserva.getDataInicial()),
					Conversor.conversorData(reserva.getDataFinal()), reserva.getHoraEntrada(), reserva.getQuarto(),
					reserva.getStatus(), reserva.getValorDiaria() });
		}
	}

	public void RecebeCliente(Cliente c) {
		cliente = c;
	}

}
